#!/bin/bash
#
# Init file for lithium
#
# chkconfig: 2345 55 25
# description: lithium Selenium Grid Replacement
#
# processname: lithium
# config: /etc/lithium.conf
# pidfile: /var/run/lithium

# source function library
. /etc/rc.d/init.d/functions

LSERV=lithium
BINDIR=/usr/bin
RETVAL=0;

start()
{
	echo -n $"Starting $LSERV  "
	"$BINDIR/$LSERV" start
	RETVAL=$?
	echo
	return $RETVAL
}

stop()
{
	echo -n $"Stopping $LSERV  "
	"$BINDIR/$LSERV" stop
	RETVAL=$?
	echo
	return $RETVAL
}

status()
{
	echo -n $"Status $LSERV  "
	"$BINDIR/$LSERV" status
	RETVAL=$?
	echo
	return $RETVAL
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		exit 1
esac
